### ISSUE TITLE
Thanos.sh 不应该包含他自己

### ISSUE THREAD

**Issue by Shonke** [hotvulcan/Thanos.sh#32]
根据原作，Thanos.sh 不应该包含他自己
确实是可能包含了他自己，但是实际结果是没有被消灭，我们理应尊重事实

**Comment by HuiguoRose** [comment]
我已经修复了这个问题 但是我fork 错了仓库 稍后我会提交PR

**Comment by HuiguoRose** [comment]
Duplicate of #36

**Comment by hotvulcan** [comment]
根据剧情，Thanos 的确可能被灭掉，但他运气比较好。。。
